### ISSUE TITLE
Weekly scrum - Nov 11th - 25th, 2024

### ISSUE THREAD

**Issue by Samimnif** [jalalmourad/SYSC4806_Group20#15]
* what have I done this week? (with link(s) to the relevant GitHub Issue(s))
* what will I do next week? (with link(s) to the relevant GitHub Issue(s))
* what is holding me back? (if applicable)
Expected length: 1-2 sentences per item

**Comment by Ibtasam-Rasool** [comment]
what have I done this week?

Fixed student topic join page issue #38. Added student availibility option #39. Worked on student report submission #37. worked on styling for login page #44. fixed bugs and refactored code.
what will I do next week?
Work on adding required features.
what is holding me back? N/A

**Comment by aarongabor1** [comment]
This week I worked on creating user accounts, password management, and login system #24. Implemented access control on controller methods and created test classes for user account functionality #34.
Next week I will work on finalizing project functionality. Nothing is currently holding me back.

**Comment by Samimnif** [comment]
* what have I done this week? (with link(s) to the relevant GitHub Issue(s))
Added UMl diagram and student Tests #41 
Added the prof availability #27 
Helped improve the Topic HTML page #17 
* what will I do next week? (with link(s) to the relevant GitHub Issue(s))
Next week we will be working on the coordinator presentation setup tool 
* what is holding me back? (if applicable)
nothing at this moment except for the presentation we are supposed to prepare for the Topic we chose.

**Comment by hadisrour6** [comment]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))
https://github.com/jalalmourad/SYSC4806_Group20/issues/25
-Added dropbox functionality to app, created the controller for dropbox:
-created the webpage for the dropbox:

what will I do next week? (with link(s) to the relevant GitHub Issue(s))

-Next week work on more test cases 
-Continue tweaking dropbox functionality

what is holding me back? (if applicable)
N/A
